# Generated by Django 5.0 on 2024-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completion', 'Completion'), ('ToDo', 'ToDo'), ('Backlog', 'Backlog')], max_length=15),
        ),
        migrations.AlterModelTable(
            name='taskdetails',
            table='TaskDetails',
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='UserDetails',
        ),
    ]
