# Generated by Django 5.0 on 2024-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_taskdetails_phases_alter_taskdetails_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdetails',
            options={'verbose_name': 'Task Details', 'verbose_name_plural': 'Task Details'},
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Backlog', 'Backlog'), ('ToDo', 'ToDo'), ('Completion', 'Completion')], max_length=15),
        ),
        migrations.AlterModelTable(
            name='taskdetails',
            table='Task Details',
        ),
    ]
