# Generated by Django 5.0 on 2024-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userdetails_options_alter_taskdetails_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Backlog', 'Backlog'), ('Completion', 'Completion'), ('ToDo', 'ToDo')], max_length=15),
        ),
    ]
