# Generated by Django 5.0 on 2024-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_taskdetails_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Backlog', 'Backlog'), ('Completion', 'Completion'), ('InProgress', 'InProgress')], max_length=15),
        ),
    ]
