# Generated by Django 5.0 on 2024-01-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_taskdetails_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completion', 'Completion'), ('ToDo', 'ToDo'), ('Backlog', 'Backlog')], max_length=15),
        ),
    ]
