# Generated by Django 5.0 on 2024-01-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_taskdetails_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='phases',
            field=models.CharField(choices=[('Completion', 'Completion'), ('InProgress', 'InProgress'), ('ToDo', 'ToDo'), ('Backlog', 'Backlog')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
